"""criado uma tabela de associacao

Revision ID: 2f532e49c2d8
Revises: 7bfa108f9118
Create Date: 2024-06-11 14:02:23.142751

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2f532e49c2d8'
down_revision = '7bfa108f9118'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_books',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['livro.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'book_id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('year_of_birth')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year_of_birth', mysql.VARCHAR(length=10), nullable=False))

    op.drop_table('user_books')
    # ### end Alembic commands ###
