"""Users adicionado

Revision ID: 622239ee4d13
Revises: 
Create Date: 2024-06-03 18:50:44.828128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '622239ee4d13'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('livro', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['title'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('livro', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
